### ISSUE TITLE
Organise String Functions

### ISSUE THREAD

**Issue by realJohnAdex** [realJohnAdex/simple_shell#8]
Combine all string manipulation functions in [str_func1.c] and [str_func.c] and rename the file to a more generic name.

**Comment by Dona-j** [comment]
Organized string functions

**Comment by realJohnAdex** [comment]
You should rename the file and remove redundant file.
Also create a PR.
Keep the issues open, until we merge.

**Comment by Dona-j** [comment]
All functions within files should be retained right

**Comment by realJohnAdex** [comment]
Yes, all functions remains.
Now that the functions are all in a single file, the second file is not useful. 
- do a `git rm filename` to remove from remote repo. And commit.

**Comment by Dona-j** [comment]
redundant file was removed while resolving issue

**Comment by realJohnAdex** [comment]
Okay, I didn't notice that. Nice work.
